// Generates src/theme.css from the current brand accent color
// (static/style.css's --accent: #9c3f5a) via Material Web's own
// color-utilities — specs/v3/15-design-system.md. Run once per seed-color
// change (`npm run gen-theme`), not on every build: the output is a
// checked-in source file, not a build artifact.
import { writeFileSync } from "fs";
import {
  themeFromSourceColor, argbFromHex, hexFromArgb,
} from "@material/material-color-utilities";

const SEED = "#9c3f5a";
const theme = themeFromSourceColor(argbFromHex(SEED));

function tokens(scheme) {
  const props = [
    "primary", "onPrimary", "primaryContainer", "onPrimaryContainer",
    "secondary", "onSecondary", "secondaryContainer", "onSecondaryContainer",
    "tertiary", "onTertiary", "tertiaryContainer", "onTertiaryContainer",
    "error", "onError", "errorContainer", "onErrorContainer",
    "background", "onBackground",
    "surface", "onSurface", "surfaceVariant", "onSurfaceVariant",
    "outline", "outlineVariant",
  ];
  return props
    .map((p) => `  --md-sys-color-${kebab(p)}: ${hexFromArgb(scheme[p])};`)
    .join("\n");
}
const kebab = (s) => s.replace(/([A-Z])/g, "-$1").toLowerCase();

const css = `/* Generated by scripts/gen-theme.mjs from seed color ${SEED} — do not
   hand-edit; change the seed and re-run \`npm run gen-theme\` instead. */
:root {
${tokens(theme.schemes.light.props)}
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${tokens(theme.schemes.dark.props)}
  }
}
:root[data-theme="dark"] {
${tokens(theme.schemes.dark.props)}
}
`;
writeFileSync("src/theme.css", css);
console.log("wrote src/theme.css from seed", SEED);
