// Generates src/theme.css from the current brand accent color
// (static/style.css's --accent: #9c3f5a) via Material Web's own
// color-utilities — specs/v3/15-design-system.md. Run once per seed-color
// change (`npm run gen-theme`), not on every build: the output is a
// checked-in source file, not a build artifact.
import { writeFileSync } from "fs";
import {
  themeFromSourceColor, argbFromHex, hexFromArgb,
} from "@material/material-color-utilities";

const SEED = "#9c3f5a";
const theme = themeFromSourceColor(argbFromHex(SEED));

// Material Web's typescale falls back to 'Roboto' (via --md-ref-typeface-
// brand/-plain) when unset — since Roboto isn't loaded as a webfont here,
// the browser substitutes its own default for that specific name, which
// doesn't necessarily match the substitution it'd pick for the generic
// stack below. Pointing both ref-typeface tokens at the exact same stack
// static/style.css's `body` rule uses (`font: 15px/1.55 ui-sans-serif,
// system-ui, -apple-system, "Segoe UI", sans-serif`) makes MD3 components
// and hand-built text resolve to the same font by construction, not by
// coincidence.
const TYPEFACE = 'ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif';

function tokens(scheme) {
  const props = [
    "primary", "onPrimary", "primaryContainer", "onPrimaryContainer",
    "secondary", "onSecondary", "secondaryContainer", "onSecondaryContainer",
    "tertiary", "onTertiary", "tertiaryContainer", "onTertiaryContainer",
    "error", "onError", "errorContainer", "onErrorContainer",
    "background", "onBackground",
    "surface", "onSurface", "surfaceVariant", "onSurfaceVariant",
    "outline", "outlineVariant",
  ];
  return props
    .map((p) => `  --md-sys-color-${kebab(p)}: ${hexFromArgb(scheme[p])};`)
    .join("\n");
}
const kebab = (s) => s.replace(/([A-Z])/g, "-$1").toLowerCase();

// Light scheme only, deliberately: static/style.css (the rest of this site)
// has no dark-mode support at all (no `prefers-color-scheme` anywhere in
// it — confirmed, not assumed). Emitting a dark variant here would flip
// these MD3 tokens under a dark OS while every hand-built element around
// them stayed light — which is exactly the bug this comment replaced: a
// dark --accent-soft row highlight next to a near-white-on-light-pink
// button with no readable contrast (both read from these tokens via
// static/style.css's `var(--md-sys-color-*, <fallback>)` mapping). Add a
// dark scheme back here only alongside real sitewide dark-mode support,
// not before.
const css = `/* Generated by scripts/gen-theme.mjs from seed color ${SEED} — do not
   hand-edit; change the seed and re-run \`npm run gen-theme\` instead.
   Light scheme only — see the comment in gen-theme.mjs for why. */
:root {
  --md-ref-typeface-brand: ${TYPEFACE};
  --md-ref-typeface-plain: ${TYPEFACE};
${tokens(theme.schemes.light.props)}
}
`;
writeFileSync("src/theme.css", css);
console.log("wrote src/theme.css from seed", SEED);
